version: '3.8'
services: 
  backend:
    image: ec2-13-51-195-57.eu-north-1.compute.amazonaws.com:5500/main/backend
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PYTHONPATH=/app
    command: 'python main.py'
    ports:
      - 8001:5000
    volumes:
      - .:/app
    depends_on:
      - db

  queue:
    image: ec2-13-51-195-57.eu-north-1.compute.amazonaws.com:5500/main/queue
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python consumer.py'
    depends_on:
      - db
  
  db:
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE: main
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    volumes:
      - .dbdata:/var/lib/mysql 
    ports:
      - 33067:3306

      
